//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicAppApi.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condition
    {
        public int Id { get; set; }
        public Nullable<int> TrackSetId { get; set; }
        public Nullable<int> OutputId { get; set; }
        public Nullable<System.DateTime> AbsoluteStartDate { get; set; }
        public Nullable<System.DateTime> AbsoluteEndDate { get; set; }
        public Nullable<System.DateTime> AnnualStartDate { get; set; }
        public Nullable<System.DateTime> AnnualEndDate { get; set; }
        public Nullable<byte> DaysOfWeek { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<byte> Priority { get; set; }
    
        public virtual Output Output { get; set; }
        public virtual TrackSet TrackSet { get; set; }
    }
}
