//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicAppApi.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class musicdbEntities : DbContext
    {
        public musicdbEntities()
            : base("name=musicdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Condition> Conditions { get; set; }
        public virtual DbSet<Output> Outputs { get; set; }
        public virtual DbSet<Play> Plays { get; set; }
        public virtual DbSet<track> tracks { get; set; }
        public virtual DbSet<TrackSet> TrackSets { get; set; }
        public virtual DbSet<Tracks_Outputs> Tracks_Outputs { get; set; }
        public virtual DbSet<Tracks_TrackSets> Tracks_TrackSets { get; set; }
    }
}
