//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicAppApi.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Play
    {
        public int Id { get; set; }
        public Nullable<int> TrackId { get; set; }
        public Nullable<int> OutputId { get; set; }
        public Nullable<System.DateTime> TimePlayed { get; set; }
    
        public virtual Output Output { get; set; }
        public virtual track track { get; set; }
    }
}
